name: CI Pipeline  # Name of the workflow

# When this workflow runs:
on:
  push:
    branches:
      - main  # Runs the workflow when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Runs the workflow when a pull request is made to 'main' branch

# The jobs to run in the pipeline
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up the environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (replace 'npm test' with your actual test command if different)
      - name: Run tests
        run: npm test
